import type { Metadata } from "next";
import "@/app/globals.css";
import Header from "@/components/Header";
import HeaderV2 from "@/components/HeaderV2";
import { AuthAside } from "@/components/auth/AuthAside";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
    title: "Авторизація єЗбір",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ua">
            <body className='bg-[#E7EEF3]'>

                <HeaderV2 />
                <main className='flex h-[700px]'>
                    {children}
                    <AuthAside />
                </main>
                <Footer />
            </body>
        </html>
    );
}
