import type { Metadata } from "next";
import "@/app/globals.css";
import HeaderV2 from "@/components/HeaderV2";
import SettingAside from "@/app/setting/components/SettingAside";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
    title: "ЄЗбір Настройки",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ua">
        <body className="bg-[#E7EEF3] h-screen flex flex-col">
        <HeaderV2 />
        <div className="flex flex-grow">
            <SettingAside />
            <main className="flex-grow bg-gray-100 p-4">
                {children}
            </main>
        </div>
        <Footer />
        </body>
        </html>
    );
}
